version: 2

builds:
  - id: telescreen
    binary: telescreen
    main: .
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/maxgio92/telescreen/pkg/cmd/version.version={{ .Version }}

archives:
  - id: telescreen
    ids: [telescreen]
    name_template: "telescreen_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - id: telescreen
    ids: [telescreen]
    package_name: telescreen
    file_name_template: "telescreen_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    vendor: maxgio92
    homepage: https://github.com/maxgio92/telescreen
    maintainer: Massimiliano Giovagnoli <maxgio92@pm.me>
    description: A screen for monitoring your daily job, in your terminal.
    license: MIT
    formats: [deb, rpm, apk]
    bindir: /usr/bin

brews:
  - name: telescreen
    ids: [telescreen]
    repository:
      owner: maxgio92
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    homepage: https://github.com/maxgio92/telescreen
    description: A screen for monitoring your daily job, in your terminal.
    license: MIT
    install: |
      bin.install "telescreen"
    test: |
      system "#{bin}/telescreen", "version"

checksum:
  name_template: "checksums.txt"

changelog:
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
