version: 2

builds:
  - id: telescreen
    binary: telescreen
    main: .
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/maxgio92/telescreen/pkg/cmd/version.version={{ .Version }}

archives:
  - id: telescreen
    ids: [telescreen]
    name_template: "telescreen_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
